// // 종합강의시간표조회 json 데이터 타입 정의
// export type RawCourseItem = {
//   SBJ_NO: string;
//   SBJ_NM: string;
//   CPDIV_CD: string | null;
//   DNN_CD: string | null;
//   ALL_FULL_PCNT: number | null;
//   SBJ_DIV: string | null;
//   OPEN_SEM_CD: string | null;
//   TMTBL_DSC: string | null;
//   DETL_CURI_CD: string | null;
//   OPEN_DPTMJR_CD_NM: string | null;
//   CDT: string | null;
//   OPEN_ORGN_CLSF_CD: string | null;
//   ROOM_DSC: string | null;
//   OPEN_YY: string | null;
//   SCHGRD: string | null;
//   REMK: string | null;
//   OPEN_DPTMJR_CD: string | null;
//   TCHR_DSC: string | null;
//   DVCLS: string | null;
//   TKCRS_PCNT: number;
// };

export type RawCourseItem = {
  ETC_EVAL5_OPEN_YN: string;
  MAIN_PROF_YN: string;
  ATND_EVAL_RATE: number;
  SCHGRD2_FULL_PCNT: number | null;
  RTEVAL_RATE_CD: string;
  CLSLESN_RESN_DSC: string | null;
  TKCRS_CDT_EXCP_YN: string;
  CDT: string;
  ETC_EVAL1_OPEN_YN: string;
  PRAC_HCNT: string;
  ETC_EVAL1_RATE: number | null;
  ETC_EVAL4_DSC: string | null;
  FNL_EVAL_RATE: number;
  LESN_REGN_CD_NM: string;
  PLAN_URL: string | null;
  LESN_LANG_TYP_CD: string | null;
  ETC_EVAL2_RATE: number | null;
  CPDIV_CD_NM: string;
  SCHGRD1_FULL_PCNT: number | null;
  CAPD_LESN_YN: string | null;
  ETC_EVAL2_DSC: string | null;
  DETL_CURI_CD_NM: string;
  ETC_EVAL4_OPEN_YN: string;
  INV_LESN_ALOW_YN: string;
  PROJ_EVAL_RATE: number;
  DMOOC_LESN_YN: string | null;
  PROF_ENG_DSC: string | null;
  TMTBL_ENG_DSC: string | null;
  OBJ_CORS_CD: string;
  TMTCH_YN: string | null;
  OBJ_SCHGRD: string;
  RECOD_EVAL_METH_CD: string;
  RECOD_GRD_TYP_CD: string;
  ALL_FULL_PCNT: number;
  ETC_EVAL5_DSC: string | null;
  SCHGRD3_FULL_PCNT: number | null;
  ETC_EVAL3_RATE: number | null;
  DETL_CURI_CD: string;
  OPEN_ORGN_CLSF_CD: string;
  COLG_NM: string;
  EGCERT_FCTR_CD: string;
  MJR_NM: string | null;
  KMOOC_LESN_YN: string | null;
  SCHGRD6_FULL_PCNT: number | null;
  BLND_LESN_YN: string | null;
  TMTBL_DUPL_ALOW_YN: string;
  CPDIV_CD: string;
  REMK_DSC: string | null;
  ETC_EVAL3_OPEN_YN: string;
  MNCLS_ALL_FULL_PCNT: number;
  RECRS_LIMT_YN: string;
  CLSLESN_DT: string | null;
  SESN_SEM_TKCRS_AMT: number;
  MID_EVAL_OPEN_YN: string;
  SBJ_KOR_EXPLN_DSC: string;
  ATNT_CMPL_SEM_TRM_NM: string | null;
  DPT_NM: string;
  ETC_EVAL1_DSC: string | null;
  LESN_TYP_CD: string;
  ETC_EVAL3_DSC: string | null;
  FNL_EVAL_OPEN_YN: string;
  SBJ_ENG_EXPLN_DSC: string;
  EMP_NM: string;
  EMP_NO: string;
  SCHGRD5_FULL_PCNT: number | null;
  UNIV_UNON_LESN_YN: string | null;
  ROOM_ENG_DSC: string | null;
  OBJ_DNN_CD: string;
  LESN_STY_CD: string;
  EDTC_LESN_YN: string | null;
  MID_RECOD_NOTI_DT: string | null;
  TMTBL_KOR_DSC: string | null;
  EGCERT_THRY_HCNT: string | null;
  ETC_EVAL5_RATE: number | null;
  OPEN_YY: string;
  EGCERT_FCTR_DETL_CD: string;
  EGCERT_YN: string;
  CDT_EXCHG_PSBL_YN: string;
  SBJ_NO: string;
  ATND_EVAL_OPEN_YN: string;
  SBJ_NM: string;
  THRY_HCNT: string;
  RECOD_GRD_TYP_CD_NM: string;
  SCHGRD4_FULL_PCNT: number | null;
  MMJR_FULL_PCNT: number | null;
  PROJ_EVAL_OPEN_YN: string;
  ETC_EVAL2_OPEN_YN: string;
  TKCRS_APPL_LIMT_YN: string;
  DVCLS: string;
  TKCRS_PCNT: number;
  ETC_EVAL4_RATE: number | null;
  MID_EVAL_RATE: number;
  SBJ_ENG_NM: string;
  ATNT_CMPL_SEM_TRM_CD: string | null;
  EVAL_TYP_CD: string | null;
  ROOM_KOR_DSC: string | null;
  FLIP_LESN_YN: string | null;
  RECOD_EVAL_METH_CD_NM: string;
  EVAL_EXCP_LESN_YN: string;
  LESN_LANG_CD: string | null;
  OPEN_SEM_CD: string;
  TKCRS_PRSN_LIMT_YN: string;
  ACTV_LESN_YN: string | null;
  EGCERT_EXPM_HCNT: string | null;
  TCHR_CAL_METH_CD: string;
  EGCERT_FORM_CDT: string;
  OPEN_DPTMJR_CD: string;
  PROF_KOR_DSC: string;
};

// 강의실별시간표조회 json 데이터 타입 정의
export type RawClassTimetable = {
  LEC_CHAIR: string;
  CURI_CD_NM: string;
  SBJ_NO: string;
  SBJ_NM: string;
  REMK_DSC: string | null;
  TKCRS_PCNT1: number;
  ALL_FULL_PCNT: number | null;
  TKCRS_PCNT2: number;
  ROOM_NM: string;
  DEPT_NM: string;
  ROOM_CD: string;
  CDT: string;
  DSC: string;
  OBJ_SCHGRD_NM: string;
  PROF_KOR_DSC: string;
  BD_CD: string;
  DVCLS: string;
  TKCRS_PCNT: number;
};
